package com.swiftdroid.posterhouse.admin.model;

import java.math.BigDecimal;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;

import org.springframework.data.annotation.LastModifiedDate;

@Entity
public class UserPayment {
@Id
@GeneratedValue
private Long id;

public String CO; // CREATED ON
public String CB; // CREATED BY
@LastModifiedDate
public String MO; // MODIFIED ON

public String MB; // MODIFIED BY
public Boolean AT; // ACTIVE STATUS
public long DT; // DEVICE TIME
public String ST; // SERVER LOG TIME
public BigDecimal amount; // AMOUNT NEED TO PAY BY USER
public String amount_paid; // AMOUNT PAID BY USER
public String currency; // CURRENCY
public String TXNID; // CODE GENERATED BY OUR SERVER
public String gatewayName; // TYPE OF PAYMENT //ORDER//SUBSCRIPTION
public String status; // PAYMENT STATUS CREATED/ATTEMPTED/PAID
public String paymentMode;
public String transectionDate;
public UserPayment() {
	super();
	// TODO Auto-generated constructor stub
}

@OneToOne
private Order order;



public Long getId() {
	return id;
}

public void setId(Long id) {
	this.id = id;
}

public String getCO() {
	return CO;
}

public void setCO(String cO) {
	CO = cO;
}

public String getCB() {
	return CB;
}

public void setCB(String cB) {
	CB = cB;
}

public String getMO() {
	return MO;
}

public void setMO(String mO) {
	MO = mO;
}

public String getMB() {
	return MB;
}

public void setMB(String mB) {
	MB = mB;
}

public Boolean getAT() {
	return AT;
}

public void setAT(Boolean aT) {
	AT = aT;
}

public long getDT() {
	return DT;
}

public void setDT(long DT) {
	DT = DT;
}

public String getST() {
	return ST;
}

public void setST(String sT) {
	ST = sT;
}

public BigDecimal getAmount() {
	return amount;
}

public void setAmount(BigDecimal amount) {
	this.amount = amount;
}

public String getAmount_paid() {
	return amount_paid;
}

public void setAmount_paid(String amount_paid) {
	this.amount_paid = amount_paid;
}



public String getCurrency() {
	return currency;
}

public void setCurrency(String currency) {
	this.currency = currency;
}






public String getTXNID() {
	return TXNID;
}

public void setTXNID(String tXNID) {
	TXNID = tXNID;
}



public String getPaymentMode() {
	return paymentMode;
}

public void setPaymentMode(String paymentMode) {
	this.paymentMode = paymentMode;
}

public String getTransectionDate() {
	return transectionDate;
}

public void setTransectionDate(String transectionDate) {
	this.transectionDate = transectionDate;
}

public String getGatewayName() {
	return gatewayName;
}

public void setGatewayName(String gatewayName) {
	this.gatewayName = gatewayName;
}

public String getStatus() {
	return status;
}

public void setStatus(String status) {
	this.status = status;
}

public Order getOrder() {
	return order;
}

public void setOrder(Order order) {
	this.order = order;
}





	
}
